name: Test

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Test Build
        run: echo "Test build executed successfully!"
